#ifndef SPI_MASTER_H
#define SPI_MASTER_H

// Include base addresses and macros
#include "chip_top.h"

// Register addresses
#define SPI_MASTER_CONTROL_REGISTER  REG_ADDR(SPI_MASTER_BASE_ADDR + 0x00)
#define SPI_MASTER_STATUS_REGISTER   REG_ADDR(SPI_MASTER_BASE_ADDR + 0x04)
#define SPI_MASTER_TX_FIFO_DATA      REG_ADDR(SPI_MASTER_BASE_ADDR + 0x08)
#define SPI_MASTER_RX_FIFO_DATA      REG_ADDR(SPI_MASTER_BASE_ADDR + 0x0C)
#define SPI_MASTER_TX_FIFO_LEVEL     REG_ADDR(SPI_MASTER_BASE_ADDR + 0x10)
#define SPI_MASTER_RX_FIFO_LEVEL     REG_ADDR(SPI_MASTER_BASE_ADDR + 0x14)
#define SPI_MASTER_CLOCK_DIVIDER_LSB REG_ADDR(SPI_MASTER_BASE_ADDR + 0x18)
#define SPI_MASTER_CLOCK_DIVIDER_MSB REG_ADDR(SPI_MASTER_BASE_ADDR + 0x1C)

//// SPI_MASTER_CONTROL_REGISTER
// control_register fields masks
#define SPI_MASTER_CONTROL_TX_FIFO_RESET_M    (0x01)
#define SPI_MASTER_CONTROL_RX_FIFO_RESET_M    (0x02)
#define SPI_MASTER_CONTROL_TX_INHIBIT_M       (0x04)
#define SPI_MASTER_CONTROL_CLOCK_POLARITY_M   (0x08)
#define SPI_MASTER_CONTROL_CLOCK_PHASE_M      (0x10)
#define SPI_MASTER_CONTROL_ENABLE_LSB_FIRST_M (0x20)
// control_register fields set
#define SPI_MASTER_CONTROL_TX_FIFO_RESET_S(val)    (val << 0)
#define SPI_MASTER_CONTROL_RX_FIFO_RESET_S(val)    (val << 1)
#define SPI_MASTER_CONTROL_TX_INHIBIT_S(val)       (val << 2)
#define SPI_MASTER_CONTROL_CLOCK_POLARITY_S(val)   (val << 3)
#define SPI_MASTER_CONTROL_CLOCK_PHASE_S(val)      (val << 4)
#define SPI_MASTER_CONTROL_ENABLE_LSB_FIRST_S(val) (val << 5)
// control_register fields get
#define SPI_MASTER_CONTROL_TX_FIFO_RESET_G(val)    ((val & SPI_MASTER_CONTROL_TX_FIFO_RESET_M) >> 0)
#define SPI_MASTER_CONTROL_RX_FIFO_RESET_G(val)    ((val & SPI_MASTER_CONTROL_RX_FIFO_RESET_M) >> 1)
#define SPI_MASTER_CONTROL_TX_INHIBIT_G(val)       ((val & SPI_MASTER_CONTROL_TX_INHIBIT_M) >> 2)
#define SPI_MASTER_CONTROL_CLOCK_POLARITY_G(val)   ((val & SPI_MASTER_CONTROL_CLOCK_POLARITY_M) >> 3)
#define SPI_MASTER_CONTROL_CLOCK_PHASE_G(val)      ((val & SPI_MASTER_CONTROL_CLOCK_PHASE_M) >> 4)
#define SPI_MASTER_CONTROL_ENABLE_LSB_FIRST_G(val) ((val & SPI_MASTER_CONTROL_ENABLE_LSB_FIRST_M) >> 5)

//// SPI_MASTER_STATUS_REGISTER
// status_register fields masks
#define SPI_MASTER_STATUS_RX_FIFO_EMPTY_M (0x01)
#define SPI_MASTER_STATUS_RX_FIFO_FULL_M  (0x02)
#define SPI_MASTER_STATUS_TX_FIFO_EMPTY_M (0x04)
#define SPI_MASTER_STATUS_TX_FIFO_FULL_M  (0x08)
// status_register fields set
#define SPI_MASTER_STATUS_RX_FIFO_EMPTY_S(val) (val << 0)
#define SPI_MASTER_STATUS_RX_FIFO_FULL_S(val)  (val << 1)
#define SPI_MASTER_STATUS_TX_FIFO_EMPTY_S(val) (val << 2)
#define SPI_MASTER_STATUS_TX_FIFO_FULL_S(val)  (val << 3)
// status_register fields get
#define SPI_MASTER_STATUS_RX_FIFO_EMPTY_G(val) ((val & SPI_MASTER_STATUS_RX_FIFO_EMPTY_M) >> 0)
#define SPI_MASTER_STATUS_RX_FIFO_FULL_G(val)  ((val & SPI_MASTER_STATUS_RX_FIFO_FULL_M) >> 1)
#define SPI_MASTER_STATUS_TX_FIFO_EMPTY_G(val) ((val & SPI_MASTER_STATUS_TX_FIFO_EMPTY_M) >>2)
#define SPI_MASTER_STATUS_TX_FIFO_FULL_G(val)  ((val & SPI_MASTER_STATUS_TX_FIFO_FULL_M) >> 3)

#endif // SPI_MASTER_H

