# Source files directory
SRC_DIR=$(TOP_DIR)/src
# Build directory
OBJ_DIR=$(TOP_DIR)/obj
# Testcases base directory
TEST_DIR=$(SRC_DIR)/sim
# Simulator to use
SIMULATOR=icarus
#SIMULATOR=questasim
# Directory where to store compiled hardware
WORK_DIR=$(OBJ_DIR)/work
# Skip dependency check
DEP_CHECK_DIS=0

# RISC-V architecture
ARCH=riscv32-unknown-elf
# Linker script path
LINKER_SCRIPT=$(SRC_DIR)/firmware/linker_script_sram.ld
# CRT0 file path
CRT0=$(SRC_DIR)/firmware/crt0.s
# Header files folder path
HEADERS=$(SRC_DIR)/firmware/headers
# GCC compilation options
OPTS=-march=rv32i -mabi=ilp32 -ffreestanding -Wl,--gc-sections -nostartfiles -I $(HEADERS) -T $(LINKER_SCRIPT)


# Target to run when no target it specified
.DEFAULT_GOAL := .error
.PHONY: .error
.error :
	@echo "Error: No target specified" >&2
	@exit 1


# Delete autogenerated files
.PHONY: clean
clean :
	rm -rf $(OBJ_DIR)/*

# Check for all necessary programs and create the obj directory
$(OBJ_DIR) :
ifeq ($(DEP_CHECK_DIS), 0)
# Check for risc-v toolchain
	@if ! which $(ARCH)-gcc > /dev/null 2>&1; then \
		echo "RISC-V toolchain: MISSING"; \
		echo "Depencency check can be disabled setting "DEP_CHECK_DIS" in base.mk"; \
		exit 1; \
	else \
		echo "RISC-V toolchain: OK"; \
	fi
# Check for ripes
	@if ! which ripes > /dev/null 2>&1; then \
		echo "Ripes: MISSING"; \
		echo "Depencency check can be disabled setting "DEP_CHECK_DIS" in base.mk"; \
		exit 1; \
	else \
		echo "Ripes: OK"; \
	fi
ifeq ($(SIMULATOR), questasim)
# Check for questasim simulator
	@if ! which vsim > /dev/null 2>&1; then \
		echo "QuestaSim: MISSING"; \
		echo "Depencency check can be disabled setting "DEP_CHECK_DIS" in base.mk"; \
		exit 1; \
	else \
		echo "QuestaSim: OK"; \
	fi
else ifeq ($(SIMULATOR), icarus)
# Check for icarus simulator and gtkwave
	@if ! which iverilog > /dev/null 2>&1; then \
		echo "Icarus: MISSING"; \
		echo "Depencency check can be disabled setting "DEP_CHECK_DIS" in base.mk"; \
		exit 1; \
	else \
		echo "Icarus: OK"; \
	fi
	@if ! which gtkwave > /dev/null 2>&1; then \
		echo "GTKWave: MISSING"; \
		echo "Depencency check can be disabled setting "DEP_CHECK_DIS" in base.mk"; \
		exit 1; \
	else \
		echo "GTKWave: OK"; \
	fi
endif
endif
# Create obj directory
	@if ! mkdir -p $(OBJ_DIR) > /dev/null 2>&1; then \
		echo "Failed to create folder $(OBJ_DIR)"; \
		exit 1; \
	else \
		echo "Folder $(OBJ_DIR) created successfully"; \
		echo "All prerequisites met"; \
	fi
