# Top directory of the project
#TOP_DIR=$(dir $(lastword $(MAKEFILE_LIST)))
TOP_DIR=/media/marco/Shared/fpga/cpu
# Source files directory
SRC_DIR=$(TOP_DIR)/src
# Build directory
OBJ_DIR=$(TOP_DIR)/obj
# Testcases base directory
TEST_DIR=$(SRC_DIR)/test
# Silumator to use
SIMULATOR=modelsim
# Directory where to store compiled hardware
WORK_DIR=$(OBJ_DIR)/work

# RISC-V architecture
ARCH=riscv32-unknown-elf
# Linker script path
LINKER_SCRIPT=$(SRC_DIR)/firmware/linker_script.ld
# CRT0 file path
CRT0=$(SRC_DIR)/firmware/crt0.s
# GCC compilation options
OPTS=-march=rv32i -mabi=ilp32 -ffreestanding -Wl,--gc-sections -nostartfiles -T $(LINKER_SCRIPT)

# Delete autogenerated files
clean :
	rm -rf $(OBJ_DIR)/*

# Check for all necessary programs and create the obj directory
$(OBJ_DIR) :
# Check for risc-v toolchain
	@if ! which $(ARCH)-gcc > /dev/null 2>&1; then \
		echo "RISC-V toolchain: MISSING"; \
		exit 1; \
	else \
		echo "RISC-V toolchain: OK"; \
	fi
# Check for ripes
	@if ! which ripes > /dev/null 2>&1; then \
		echo "Ripes: MISSING"; \
		exit 1; \
	else \
		echo "Ripes: OK"; \
	fi
ifeq ($(SIMULATOR), modelsim)
# Check for modelsim simulator
	@if ! which vsim > /dev/null 2>&1; then \
		echo "Modelsim: MISSING"; \
		exit 1; \
	else \
		echo "Modelsim: OK"; \
	fi
else ifeq ($(SIMULATOR), icarus)
# Check for icarus simulator
	@if ! which iverilog > /dev/null 2>&1; then \
		echo "Icarus: MISSING"; \
		exit 1; \
	else \
		echo "Icarus: OK"; \
	fi
endif
# Create obj directory
	@if ! mkdir -p $(OBJ_DIR) > /dev/null 2>&1; then \
		echo "Failed to create folder $(OBJ_DIR)"; \
		exit 1; \
	else \
		echo "Folder $(OBJ_DIR) created successfully"; \
		echo "All prerequisites met"; \
	fi
